# Generated by Django 5.1.6 on 2025-02-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Men'), ('SW', 'Women'), ('OW', 'Kids')], max_length=2),
        ),
    ]
