# Generated by Django 5.1.2 on 2025-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shoe_category_alter_address_id_alter_coupon_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
