# Generated by Django 5.2.3 on 2025-09-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutmodel_clientmodel_contactmodel_features_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BR', 'Branded'), ('PM', 'Photo Mount'), ('PK', 'Package')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('B', 'Best Seller'), ('O', 'Offer')], max_length=1),
        ),
    ]
