# Generated by Django 5.2.3 on 2025-09-10 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity for package'),
        ),
        migrations.AddField(
            model_name='item',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special package price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('B', 'Best Seller'), ('O', 'Offer')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3+', 'A3+'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.item')),
            ],
        ),
    ]
