# Generated by Django 5.2.3 on 2025-09-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_item_discount_price_remove_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3+', 'A3+'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=4),
        ),
    ]
