# Generated by Django 5.2.3 on 2025-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BR', 'Branded'), ('PM', 'Photos'), ('PK', 'Package'), ('DS', 'Design')], max_length=2),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3+', 'A3+'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('MN', 'Minimun')], max_length=4),
        ),
    ]
