# Generated by Django 5.2.3 on 2025-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_item_category_alter_itemsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BR', 'Branded'), ('PM', 'Photo Mount'), ('PK', 'Package'), ('DS', 'Design')], max_length=2),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.CharField(max_length=4),
        ),
    ]
