# Generated by Django 5.2.3 on 2025-09-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BR', 'Branded'), ('PM', 'Photo Mount'), ('PK', 'Package')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3+', 'A3+'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=4),
        ),
    ]
