# Generated by Django 5.2.3 on 2025-10-06 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_orderitem_color_orderitem_price_orderitem_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('user', 'item', 'size', 'color', 'ordered')},
        ),
    ]
