# Generated by Django 5.2.3 on 2025-10-08 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_itemtype_alter_orderitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('user', 'item', 'size', 'color', 'ordered')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_type',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
