# Generated by Django 5.2.3 on 2025-10-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_orderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BR', 'Branded'), ('PM', 'Photo Mount'), ('PK', 'Package'), ('DS', 'Design')], max_length=2),
        ),
    ]
