# Generated by Django 5.0.5 on 2024-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='para2',
            field=models.TextField(default='default_value'),
        ),
    ]
