# Generated by Django 5.0.5 on 2024-06-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_portfolioimage_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('project_date', models.DateField()),
                ('project_url', models.URLField()),
                ('tagline', models.TextField(default='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='blog.portfolio_details')),
            ],
        ),
    ]
