# Generated by Django 5.0.5 on 2024-06-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_aboutmodel_slug_remove_clientmodel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='icon_des',
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('icon_des', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='blog.aboutmodel')),
            ],
        ),
    ]
