# Generated by Django 5.0.5 on 2024-06-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_aboutmodel_icon_des_listitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='icon',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='icon_des',
            field=models.CharField(max_length=250),
        ),
    ]
