# Generated by Django 5.0.5 on 2024-06-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_servicemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='description',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='icon_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='blog.servicemodel')),
            ],
        ),
    ]
