# Generated by Django 5.2.3 on 2025-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_servicemodel_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('customized-branding', 'Customized-branding'), ('graphics-design', 'Graphics-design'), ('large-format-printing', 'Large-format-printing'), ('photography-videography', 'Photography-videography')], max_length=100),
        ),
    ]
