# Generated by Django 5.2.3 on 2025-07-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_hero_options_remove_hero_icon_hero_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={},
        ),
        migrations.RemoveField(
            model_name='hero',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='order',
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.hero')),
            ],
        ),
    ]
