# Generated by Django 5.0.5 on 2024-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_servicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/assets/img/')),
                ('tagline', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('icon_des', models.TextField()),
                ('para1', models.TextField()),
            ],
        ),
    ]
