# Generated by Django 5.0.5 on 2024-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_clientmodel_features_team_testimonials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('counter_end', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='features',
            name='counter_end',
        ),
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
