# Generated by Django 5.0.5 on 2024-06-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('details_url', models.URLField()),
            ],
        ),
    ]
