# Generated by Django 5.0.5 on 2024-06-01 06:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='details_url',
            field=models.CharField(max_length=100),
        ),
    ]
