# Generated by Django 5.0.5 on 2024-06-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_portfolio_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='details_url',
            field=models.URLField(),
        ),
    ]
