# Generated by Django 5.0.5 on 2024-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_portfolio_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_details',
            name='tagline',
            field=models.TextField(default=''),
        ),
    ]
