# Generated by Django 5.0.5 on 2024-06-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_portfolioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_details',
            name='images',
        ),
    ]
