# Generated by Django 5.0.5 on 2024-06-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_portfolio_details_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_details',
            name='images',
            field=models.JSONField(default='null'),
        ),
    ]
