# Generated by Django 5.0.5 on 2024-06-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_aboutmodel_slug_clientmodel_slug_counts_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='counts',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='features',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='portfolio_details',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
