# Generated by Django 5.0.5 on 2024-06-06 10:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_aboutmodel_icon_alter_listitem_icon_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service', unique=True),
        ),
    ]
