# Generated by Django 5.2.3 on 2025-07-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_delete_team_alter_portfolio_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counts',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
