# Generated by Django 5.2.3 on 2025-07-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_delete_counts_delete_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='hero',
            name='icon',
        ),
        migrations.AddField(
            model_name='hero',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
